import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowDown, ArrowRight, ArrowUpRight, Asterisk, Camera, Clapperboard, Mail, MoveUpRight, PenTool, Scissors, Sparkles, Check } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { ProjectCard } from '@/components/portfolio/project-card';
import { ScrollMotion } from '@/components/portfolio/motion';
import { usePortfolio } from '@/components/portfolio/store';
import { categories } from '@/lib/portfolio-data';
import hero from '@/assets/hero-collage.jpg';
export const Route = createFileRoute('/')({ head: () => ({ meta: [{ title: 'Raka Pratama — Visual Creator & Designer' }, { name: 'description', content: 'Desain yang berani. Cerita yang berarti. Portofolio desain grafis, fotografi, video, dan editing Raka Pratama.' }, { property: 'og:title', content: 'Raka Pratama — Visual Creator & Designer' }, { property: 'og:description', content: 'Eksplorasi visual, karya terpilih, dan cerita di balik proses kreatif.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }), component: Home });
const services = [{ icon: PenTool, title: 'Desain Grafis', copy: 'Identitas visual yang bukan cuma dilihat, tapi diingat.', label: 'Branding / Visual Identity / Digital', color: 'service-yellow' }, { icon: Camera, title: 'Fotografi', copy: 'Momen, ruang, dan emosi. Diceritakan lewat satu frame.', label: 'Portrait / Product / Editorial', color: 'service-mint' }, { icon: Clapperboard, title: 'Videografi', copy: 'Cerita yang bergerak. Dari ide pertama sampai frame terakhir.', label: 'Commercial / Short Film / Content', color: 'service-pink' }, { icon: Scissors, title: 'Editing', copy: 'Menyatukan potongan menjadi cerita yang utuh.', label: 'Video Editing / Color / Motion', color: 'service-blue' }];
const steps = [{ title: 'Kenalan & brief', text: 'Kita ngobrol dulu. Tentang ide lo, tujuan brand, dan apa yang pengen kita capai bareng.' }, { title: 'Riset & eksplorasi', text: 'Mencari referensi, memahami audiens, dan menghubungkan ide lewat moodboard yang terarah.' }, { title: 'Bikin jadi nyata', text: 'Saatnya mengubah ide jadi visual. Eksperimen, eksekusi, dan detail yang dipikirin sampai tuntas.' }, { title: 'Polish & delivery', text: 'Feedback, revisi, lalu sentuhan terakhir. Karya siap dipakai, lengkap dengan semua file yang lo butuhin.' }];
function Home() {
 const { projects } = usePortfolio(); const [filter, setFilter] = useState('Semua'); const [step, setStep] = useState(0); const [quote, setQuote] = useState(0); const [sent, setSent] = useState(false);
 const testimonials = [{ text: 'Raka nggak cuma ngerti brief, tapi juga ngasih perspektif yang bikin hasilnya jauh lebih keren dari ekspektasi.', name: 'Dinda Putri', role: 'Founder, Matcha Club' }, { text: 'Detail, komunikatif, dan selalu punya ide segar. Proses kerja bareng Raka terasa seperti kolaborasi, bukan transaksi.', name: 'Arif Setiawan', role: 'Creative Director, Ruang Studio' }];
 function contact(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (data.get('website')) return; const body = `Nama: ${data.get('name')}\nEmail: ${data.get('email')}\n\n${data.get('message')}`; window.location.href = `mailto:hello@example.com?subject=${encodeURIComponent('Kolaborasi kreatif baru')}&body=${encodeURIComponent(body)}`; setSent(true); }
 return <main id="top"><ScrollMotion/><section className="hero" aria-labelledby="hero-title"><img className="hero-backdrop" src={hero} width={1536} height={1024} alt="Kolase kreator visual dengan kamera analog" fetchPriority="high"/><div className="hero-content"><div className="availability"><span/> TERBUKA UNTUK KOLABORASI</div><p className="hero-intro">Halo, gue Raka <span className="wave">✳</span></p><h1 id="hero-title">VISUAL<br/>THINKER.<br/><span className="outlined-title">STORY</span><span className="title-star">✳</span><br/><span className="highlight-title">MAKER.</span></h1><p className="hero-description">Desainer grafis, fotografer, dan pembuat cerita.<br/>Mengubah ide jadi visual yang <strong>nggak biasa.</strong></p><div className="hero-actions"><Button variant="brutal" asChild><a href="#work">Eksplor karya gue <ArrowUpRight/></a></Button><Button variant="brutalOutline" asChild><a href="#contact">Bikin sesuatu bareng <ArrowRight/></a></Button></div></div><div className="hero-note">a little chaos.<br/>a lot of intention.<MoveUpRight size={30}/></div><div className="role-sticker"><Sparkles size={20}/><span>DESIGNER BY DAY.<br/><strong>EXPLORER ALWAYS.</strong></span></div><div className="hero-bottom"><a href="#about"><ArrowDown size={16}/> SCROLL BUAT KENALAN</a><span>BASED IN INDONESIA · AVAILABLE WORLDWIDE ↗</span></div></section>
 <div className="ticker" aria-hidden="true"><div>{[0,1,2].map(n => <span key={n}>DESIGN WITH PURPOSE <Asterisk/> CAPTURE THE FEELING <Asterisk/> MAKE IT MOVE <Asterisk/> NOT JUST PRETTY <Asterisk/></span>)}</div></div>
 <section id="about" className="section about-section"><div className="section-label"><span>01 / TENTANG GUE</span><Asterisk/></div><div className="about-grid"><div className="about-title reveal"><h2>Bukan cuma<br/>bikin bagus.<br/><span className="text-primary">Bikin berarti.</span></h2><span className="handwritten">curiosity is my superpower ↗</span></div><div className="about-copy reveal"><p>Gue Raka Pratama. Kreator visual yang percaya kalau setiap ide punya cerita yang layak diceritain.</p><p>Dari desain identitas brand, menangkap momen lewat lensa, sampai menyusun frame jadi cerita — gue suka menjelajah batas antara seni, teknologi, dan kehidupan sehari-hari.</p><div className="about-stats"><div><strong>4<span>+</span></strong><span>TAHUN BERKARYA</span></div><div><strong>30<span>+</span></strong><span>PROYEK SELESAI</span></div><div><strong>∞</strong><span>RASA PENASARAN</span></div></div></div></div></section>
 <section id="services" className="section services-section"><div className="section-label"><span>02 / APA YANG GUE BIKIN</span><span>IDE LO, KITA BIKIN NYATA.</span></div><div className="section-heading reveal"><h2>Satu kreator.<br/>Banyak kemungkinan<span className="text-primary">.</span></h2><p>Visual yang punya karakter.<br/>Dari konsep sampai hasil akhir.</p></div><div className="services-grid">{services.map((s, i) => <article key={s.title} className={`service-card ${s.color} reveal`}><div className="service-top"><s.icon size={34} strokeWidth={1.7}/><span>0{i+1}</span></div><h3>{s.title}</h3><p>{s.copy}</p><div className="service-bottom"><span>{s.label}</span><ArrowUpRight size={23}/></div></article>)}</div></section>
 <section id="work" className="section work-section"><div className="section-label"><span>03 / KARYA TERPILIH</span><span>LESS TALK. MORE WORK.</span></div><div className="section-heading reveal"><h2>Ide yang jadi <span className="text-primary">nyata.</span><Asterisk className="heading-star" size={54}/></h2><Button variant="brutalOutline" asChild><Link to="/works">Semua karya <ArrowUpRight/></Link></Button></div><div className="filter-row" aria-label="Filter karya">{categories.map(c => <Button key={c} variant={filter === c ? 'chipActive' : 'chip'} onClick={() => setFilter(c)}>{c}{c === 'Semua' && <span>{projects.filter(p => p.status === 'published').length.toString().padStart(2,'0')}</span>}</Button>)}</div><div className="featured-gallery">{projects.filter(p => p.status === 'published' && (filter === 'Semua' ? p.featured : p.category === filter)).map(p => <ProjectCard project={p} key={p.id}/>)}</div></section>
 <section id="process" className="section process-section"><div className="section-label"><span>04 / CARA GUE KERJA</span><span>GOOD WORK IS A TEAM SPORT.</span></div><div className="process-grid"><h2 className="reveal">Dari “gimana<br/>kalau…” jadi<br/><span className="highlight-title">“ini dia!”</span></h2><div className="process-panel"><div className="step-tabs">{steps.map((s,i) => <Button key={s.title} variant={i === step ? 'chipActive' : 'chip'} onClick={() => setStep(i)} aria-label={`Langkah ${i+1}: ${s.title}`}>0{i+1}</Button>)}</div><span className="process-number">0{step+1}<ArrowUpRight size={70}/></span><h3>{steps[step]?.title}</h3><p>{steps[step]?.text}</p><Button variant="ghost" className="next-step" onClick={() => setStep((step+1)%steps.length)}>Langkah berikutnya <ArrowRight/></Button></div></div></section>
 <section className="section tools-section"><div className="section-label"><span>05 / CREATIVE TOOLKIT</span><span>TOOLS CHANGE. CURIOSITY DOESN’T.</span></div><div className="tools-row">{['Photoshop', 'Illustrator', 'Figma', 'Premiere Pro', 'After Effects', 'Lightroom'].map((tool,i) => <div key={tool}><span className={`tool-icon tool-${i}`}>{['Ps','Ai','F','Pr','Ae','Lr'][i]}</span><span>{tool}</span></div>)}</div></section>
 <section className="section testimonials-section"><div className="section-label"><span>06 / KATA MEREKA</span><div><Button variant="ghost" size="icon" aria-label="Testimoni sebelumnya" onClick={() => setQuote((quote+1)%2)}>←</Button><Button variant="ghost" size="icon" aria-label="Testimoni berikutnya" onClick={() => setQuote((quote+1)%2)}>→</Button></div></div><div className="quote-grid"><span className="quote-mark">“</span><div><blockquote>{testimonials[quote]?.text}</blockquote><div className="quote-person"><span className="person-avatar">{testimonials[quote]?.name.split(' ').map(s => s[0]).join('')}</span><div><strong>{testimonials[quote]?.name}</strong><p>{testimonials[quote]?.role}</p></div><span className="quote-pagination">0{quote+1} / 02</span></div></div></div></section>
 <section id="contact" className="section contact-section"><div className="section-label"><span>07 / NEXT CHAPTER</span><span><span className="status-dot"/> OPEN FOR GOOD PROJECTS</span></div><div className="contact-grid"><div><h2>PUNYA IDE<br/><span className="outlined-title">SERU?</span><ArrowUpRight className="contact-arrow"/></h2><p>Yuk, bikin sesuatu yang layak diingat.<br/>Cerita lo berikutnya dimulai dari sini.</p><a className="contact-email" href="mailto:hello@example.com">hello@example.com <ArrowUpRight/></a><span className="sample-note">Kontak contoh · detail asli menyusul</span></div><form onSubmit={contact}><label>Nama lo<input name="name" required placeholder="Siapa yang bakal jadi partner gue?"/></label><label>Email<input type="email" name="email" required placeholder="nama@email.com"/></label><label>Ceritain idenya<textarea name="message" required minLength={10} placeholder="Tentang proyek, mimpi, atau sekadar say hi…" rows={3}/></label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/><Button variant="brutal" type="submit">{sent ? <><Check/>Lanjutkan di aplikasi email</> : <>Mulai percakapan <ArrowUpRight/></>}</Button>{sent && <p role="status" className="form-note">Draft dibuka di aplikasi email. Pesan belum dikirim dari situs ini.</p>}<p className="privacy-note"><Mail size={13}/> Email lo cuma untuk ngobrolin proyek ini.</p></form></div></section>
 </main>;
}
