import { createFileRoute } from '@tanstack/react-router';
import { Search, Asterisk } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { ProjectCard } from '@/components/portfolio/project-card';
import { usePortfolio } from '@/components/portfolio/store';
import { categories } from '@/lib/portfolio-data';
export const Route = createFileRoute('/works/')({ head: () => ({ meta: [{ title: 'Semua Karya — Raka Pratama' }, { name: 'description', content: 'Arsip desain grafis, fotografi, video, dan editing Raka Pratama.' }, { property: 'og:title', content: 'Semua Karya — Raka Pratama' }, { property: 'og:description', content: 'Eksplorasi ide, visual, dan cerita dalam koleksi karya Raka.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }), component: Works });
function Works() { const { projects } = usePortfolio(); const [category, setCategory] = useState('Semua'); const [search, setSearch] = useState(''); const items = projects.filter(p => p.status === 'published' && (category === 'Semua' || p.category === category) && p.title.toLowerCase().includes(search.toLowerCase())); return <main id="top" className="archive section"><div className="section-label"><span>THE WORK / 2025—2026</span><Asterisk/></div><h1>BUKAN CUMA<br/><span className="text-primary">IDE.</span> INI KARYA.</h1><div className="archive-toolbar"><div className="filter-row">{categories.map(c => <Button variant={category === c ? 'chipActive' : 'chip'} key={c} onClick={() => setCategory(c)}>{c}</Button>)}</div><label className="search-input"><Search size={18}/><input aria-label="Cari proyek" placeholder="Cari karya…" value={search} onChange={e => setSearch(e.target.value)}/></label></div><div className="archive-grid">{items.map(project => <ProjectCard key={project.id} project={project}/>)}</div>{!items.length && <div className="empty-state"><Search size={35}/><h3>Belum ada karya yang cocok.</h3><Button variant="brutalOutline" onClick={() => { setSearch(''); setCategory('Semua'); }}>Reset filter</Button></div>}</main>; }
